version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  api:
    build: ./apiGeekURL
    ports:
    - "3001:3001"
    command: npm run start
    depends_on:
    - mongo
    - redis
  web:
     build: ./geekurl
     ports:
     - "8000:80"
     links:
     - api